---
title: "SP500 Sub Industries Report"
author: "ETF Researcher"
date: "April 14, 2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Read Data for S&P 500 Companies 
```{r message=FALSE, warning=FALSE}
library(readr)
library(quantmod)
library(PerformanceAnalytics)
library(dplyr)
companylist <- read_csv("sp500.csv") # prepared in excel
stockSymbols <- companylist["Symbol"]
```

## Number of Stocks in Each Sector
```{r}
companylist$`GICS Sector` <- factor(companylist$`GICS Sector`)
table(companylist$`GICS Sector`)
```
## Remove Symbols that Failed to Download
```{r}
companylist <- subset(companylist, Symbol != "COP" & Symbol != "CXO" & Symbol != "FOX")
table(companylist$`GICS Sector`)
```

## Get Stocks Data from Yahoo Finance

* Define a function to obtain data and cancleChart for Sub Industries

```{r}
get_data_sub <- function(sub, start_date){
  sampledStocks <- subset(companylist, `GICS Sector` == sub)
  idx <- sample(nrow(sampledStocks), 5)
  sampledStocks <- sampledStocks[idx, ]
  # store data in a new environment
  stocksEnv <- new.env()
  getSymbols(sampledStocks$Symbol, env = stocksEnv, 
           from = start_date, src = "yahoo")
  
  # produce candleChart for selected stocks
  for (stock in sampledStocks$Symbol) {
    chartSeries(stocksEnv[[stock]], 
            theme="white", 
            name = stock,
            TA="addVo();
            addRSI(14); 
            addSMA(20); addSMA(50); addSMA(200);
            addMACD(fast=12,slow=26,signal=9,type='EMA')")
  }
  
}
```

```{r}
for (sub in unique(companylist$`GICS Sector`)) {
  cat(sub, '----- \n')
  get_data_sub(sub, "2021-01-01")
  
}
```


## Appendix I Sub Industries

### Sub Industries
```{r}
# table(companylist$`GICS Sub-Industry`)
```