---
title: "SP500 Sub Industries Report"
author: "ETF Researcher"
date: "April 14, 2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Read Data for S&P 500 Companies 
```{r message=FALSE, warning=FALSE}
library(readr)
library(quantmod)
library(PerformanceAnalytics)
library(dplyr)
companylist <- read_csv("symbols500.csv") # prepared in excel
stockSymbols <- companylist["Symbol"]
```

## Number of Stocks in Each Sector
```{r}
companylist$`GICS Sector` <- factor(companylist$`GICS Sector`)
table(companylist$`GICS Sector`)
```
## Remove Symbols that Failed to Download
```{r}
companylist <- subset(companylist, Symbol != "COP" & Symbol != "CXO" & Symbol != "FOX")
table(companylist$`GICS Sector`)
```

## Get Stocks Data from Yahoo Finance

* Define a function to obtain data and cancleChart for Sub Industries

```{r}
get_data_sub <- function(sub, start_date, selectedStd, selectedRtn){
  sampledStocks <- subset(companylist, `GICS Sub-Industry` == sub)
  
  # store data in a new environment
  stocksEnv <- new.env()
  getSymbols(sampledStocks$Symbol, env = stocksEnv, 
           from = start_date, src = "yahoo")
  

  # produce return report
  goodCandidate <- data.frame()

  for (stock in sampledStocks$Symbol) {
    dret <- dailyReturn(stocksEnv[[stock]])
    pret <- Return.cumulative(dret)
    if (sd(dret) < selectedStd && as.numeric(pret) > selectedRtn) {
      tmp <- data.frame(Symbol = stock, 
                        sd = round(sd(dret), 3), 
                        ret = round(as.numeric(pret), 3))
      goodCandidate <- rbind(goodCandidate, tmp)
      
    }
  }
  
  # check the list
  # goodCandidate
  
  # produce candleChart for selected stocks
  for (stock in goodCandidate$Symbol) {
  candleChart(stocksEnv[[stock]], name = stock)
  }
  
  goodCandidate
  
}
```

```{r}
for (sub in sort(companylist$`GICS Sub-Industry`)) {
  cat(sub, '----- \n')
  get_data_sub(sub, '2021-01-01', 0.05, 0.01)
  
}
```


## Appendix I Sub Industries

### Sub Industries
```{r}
# table(companylist$`GICS Sub-Industry`)
```