---
title: "Long term or mid-term trend"
author: "ETF Researcher"
date: "4/29/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data from Yahoo Finance
```{r message=FALSE, warning=FALSE}
library(quantmod)
library(ggplot2)
library(dplyr)
library(fpp2)
```
```{r warning=FALSE}
stock_list <- c("SPY", "QQQ")
getSymbols(stock_list, from = '2021-01-01', src = "yahoo")
```

```{r warning=FALSE}
# convert the time and data into a dataframe
stocks_df <- data.frame(Date = index(SPY), 
                        SPY_Price = as.numeric(Cl(SPY)),
                        QQQ_Price = as.numeric(Cl(QQQ)))
names(stocks_df) <- c("Date", "SPY_Price", "QQQ_Price")
stocks_df$Year_Month <- format(as.Date(stocks_df$Date), "%Y-%m")
stocks_df$Year_Month <- as.factor(stocks_df$Year_Month)
head(stocks_df)
```

```{r}
stocks_df %>% ggplot(aes(x = Year_Month, y = SPY_Price, group = Year_Month)) +
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))+
    xlab("")+
    labs(title = "SPY Price Boxplot Monthly")
```

```{r}
stocks_df %>% ggplot(aes(x = Year_Month, y = QQQ_Price, group = Year_Month)) +
    geom_boxplot()+
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))+
    xlab("")+
    labs(title = "QQQ Price Boxplot Monthly")
```
